## Netlify configuration for the Instagram Link Manager
[build]
  command = "npm ci && npm run build"
  publish = "build"
  functions = "netlify/functions"

[context.production.environment]
  # Ensure Netlify uses Node 18 for production builds
  NODE_VERSION = "18"
[build]
  publish = "build"
  command = "npm run build"
  functions = "./netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
